vscode:
  extensions:
    - fivethree.vscode-ionic-snippets@1.7.1:u6NG/7KskZ8Usfdu0Y/MuQ==
    - aaron-bond.better-comments@2.0.5:YKNfOclR4e8XAxlj4xp2AA==
    - esbenp.prettier-vscode@2.3.0:1F0Pvb/ORZ/T+b60LIMs8w==
    - steoates.autoimport@1.5.3:ssEPucpXsRjqSbJX1bW0YA==
    - formulahendry.auto-rename-tag@0.1.0:/DaYBGQJ0OJXTfLl4zwBLA==
    - formulahendry.auto-close-tag@0.5.6:oZ/8R2VhZEhkHsoeO57hSw==
    - Mikael.Angular-BeastCode@8.0.10:J7aGjVXXDeyuqnhsk+vMYw==
    - johnpapa.Angular2@8.1.1:5n047Q4w8oMstLXJadb7tg==
    - batisteo.vscode-django@0.19.0:GOHmg6fGCbzkKe2S73i7Ig==
    - ms-python.python@2019.10.44104:fKYRb8X8FA37fMd+hgvv2A==
    - xabikos.JavaScriptSnippets@1.7.2:XXmiw8r7K3Guifex/E73aQ==
    - abusaidm.html-snippets@0.2.1:7b7Vkkp6Lem9WOqKCYMq2w==
    - felixfbecker.php-intellisense@2.3.13:dIFTPCKFV+ChjvesjnZhCA==
    - vscode-icons-team.vscode-icons@9.5.0:dcvbiJm3ipHVkZXodLCtUA==
    - eg2.tslint@1.0.44:3C/9/4VxeLePYcf3QXEZsQ==
    - christian-kohler.npm-intellisense@1.3.0:yQtCdwoyo890Bn9NOEuEDA==
    - ecmel.vscode-html-css@0.2.3:RBTpzQbz8rn5KTlc82tnsQ==
    - christian-kohler.path-intellisense@1.4.2:QnOrf5fk6KiVaQs4cNEP+w==
    - Zignd.html-css-class-completion@1.19.0:b3YWQQIEP1z3u93nyLX0UA==
    - CoenraadS.bracket-pair-colorizer@1.0.61:fqPT1sJEqaEdrfXeYbdW+A==
    - eg2.vscode-npm-script@0.3.9:FTjGx1Gmz+E5EP1FHaYLqQ==
    - tht13.python@0.2.3:1RPVn9AW+lkCOD6zUWqiIw==
    - ms-vscode.vscode-typescript-tslint-plugin@1.2.2:Jw3ra3MlKUzHrWQODXxjUw==
    - DotJoshJohnson.xml@2.5.0:j/V3fdZHhHApG0UDF9KLqA==
    - axosoft.gitkraken-glo@1.1.0:mYsqLejysyS918uPBrpT/A==